# Generated by Django 3.2.11 on 2022-01-19 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.TextField(default='', max_length=50)),
                ('product_description', models.TextField(default='', max_length=200)),
                ('product_price', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
    ]
