# Generated by Django 3.2.11 on 2022-01-19 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_stock_warehouse'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='product_price',
            new_name='msrp',
        ),
    ]
