# Generated by Django 3.2.11 on 2022-01-19 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_rename_product_price_product_msrp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='msrp',
            new_name='product_msrp',
        ),
    ]
