# Generated by Django 3.2.11 on 2022-01-19 20:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_rename_msrp_product_product_msrp'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.TextField(default='', max_length=20)),
                ('state', models.TextField(default='', max_length=2)),
                ('zipcode', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.RenameField(
            model_name='stock',
            old_name='product',
            new_name='product_id',
        ),
        migrations.RenameField(
            model_name='stock',
            old_name='warehouse',
            new_name='warehouse_id',
        ),
        migrations.RemoveField(
            model_name='warehouse',
            name='city',
        ),
        migrations.RemoveField(
            model_name='warehouse',
            name='state',
        ),
        migrations.RemoveField(
            model_name='warehouse',
            name='zipcode',
        ),
        migrations.AddField(
            model_name='warehouse',
            name='city_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='inventory.city'),
            preserve_default=False,
        ),
    ]
